### ISSUE TITLE
plugin_description.xml missing from deb package

### ISSUE THREAD

**Issue by chrisspen** [PR2/pr2_hack_the_future#2]
I've installed all the ros-indigo-\* packages on Ubuntu 14.04, and when I run Rviz I get the error:

```
[ERROR] [1430107225.314958023]: Skipping XML Document "/opt/ros/indigo/share/rviz_backdrop/plugin_description.xml" which had no Root Element.  This likely means the XML is malformed or missing.
```

presumably because the file `/opt/ros/indigo/share/rviz_backdrop/plugin_description.xml` does not exist. I believe this file should be included in the deb package.

**Comment by gavanderhoorn** [comment]
From [Rviz error skipping XML document](http://answers.ros.org/question/207967/rviz-error-skipping-xml-document/) on ROS Answers.

**Comment by wkentaro** [comment]
same problem

**Comment by wjwwood** [comment]
I pushed a fix to a new `indigo-devel` branch and released a new version into Indigo: https://github.com/ros/rosdistro/pull/10006

I think it should fix the problem. If someone else could test the `indigo-devel` branch I'd appreciate it. Closing for now, feel free to comment if it is not fixed.

**Comment by trainman419** [comment]
I have confirmed that this fixes the rviz error at startup.

**Comment by wjwwood** [comment]
Thanks for checking.
